# Generated by Django 4.2.30 on 2026-09-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('$', 'USD ($)'), ('€', 'EUR (€)'), ('£', 'GBP (£)'), ('₹', 'INR (₹)'), ('¥', 'JPY (¥)'), ('A$', 'AUD (A$)'), ('C$', 'CAD (C$)'), ('CHF', 'CHF')], default='$', max_length=5),
        ),
    ]
