# Generated by Django 4.2.30 on 2026-09-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='expense_docs/'),
        ),
    ]
